### ISSUE TITLE
Background image in HEADER is not responsive

### ISSUE THREAD

**Issue by Robert-M-Muench** [StartBootstrap/startbootstrap-grayscale#184]
The other images behave gentle, but the header image not. IMO it should dynamically resize to always fit on screen, without being cropped, repeated, or anything else disturbing the layout.

**Comment by davidtmiller** [comment]
The `background-size` CSS property determines the responsive dimensions of the background image. The `cover` value will cut or crop the image when the screen is resized. Without that, there would be whitespace to the sides of the image, there is no way to add to an image, but we can crop parts away.

If you want dynamic responsiveness of a background image, you can use media queries to use a different background image for different responsive screen sizes.
