### ISSUE TITLE
Safari: nav bar does not return to transparent state on scroll up

### ISSUE THREAD

**Issue by rleegates** [StartBootstrap/startbootstrap-grayscale#190]
As the title suggests on Safari 12.1.2 (14607.3.9) the nav bar does not return to transparent background when scrolling back to the top of the page but stays white instead, making the text unreadable.

**Comment by davidtmiller** [comment]
Testing it out now it seems to be working in the latest Safari, so I will close this for the time being and keep an eye on it. Thanks!
