### ISSUE TITLE
index.html missing

### ISSUE THREAD

**Issue by minhaz725** [StartBootstrap/startbootstrap-grayscale#202]
I'm relatively new to these stuffs, so please don't laugh. I can't find the index.html. Am I missing something or is this a bug?

**Comment by davidtmiller** [comment]
It's not a bug! If you go to `dist` you will see the flattened down, compiled project. The `src` file and all of the files in the root are things used for development purposes. More advanced developers want access to these sorts of files, but if you just want to work with vanilla HTML you can ignore everything except for what is in the `dist` folder!

**Comment by minhaz725** [comment]
ok thank you!
